name: "Feature Request"
description: "Propose a user-facing feature or capability."
title: "[Feature]: "
labels: ["type: feature", "status: triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What user/problem does this solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: What should we build?
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options: [critical, high, medium, low]
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Effort Estimate
      options: ["XS (≤2h)", "S (≤1d)", "M (2–4d)", "L (1–2w)", "XL (2w+)"]
    validations:
      required: true
